version: '3'
services:
  postgres:
    image: vveritech/calculator_postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: on-failure

  calculator:
    image: vveritech/calculator_api
    ports:
      - 8081:8081
    restart: on-failure
  
volumes:
  postgresql:
